###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: meuclipp-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=meuclipp

    webserver:
      image: nginx:alpine
      container_name: meuclipp-webserver
      volumes:
          - ./meuclipp/front/:/var/www/html
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: meuclipp-php-fpm
      working_dir: /application
      volumes:
        - ./meuclipp/front/:/var/www/html
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

